name: testingtopchimp
favicon: null
layout_spectrum: 0.87793
typography_spectrum: 0.9583988713566214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeede9'
    - '#171314'
    - '#615d54'
    - '#df8f9a'
    - '#00768e'
  brandStrength: 0.6609443768393248
  lightness: 0.5223901893477887
  saturation: 0.7188830063678324
  rhythmicContrast: 0.09498724481090903
purpose: []
